// Generated by gencpp from file beginner_tutorials/action_expect_utility.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ACTION_EXPECT_UTILITY_H
#define BEGINNER_TUTORIALS_MESSAGE_ACTION_EXPECT_UTILITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct action_expect_utility_
{
  typedef action_expect_utility_<ContainerAllocator> Type;

  action_expect_utility_()
    : left(0.0)
    , keep(0.0)
    , right(0.0)  {
    }
  action_expect_utility_(const ContainerAllocator& _alloc)
    : left(0.0)
    , keep(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef float _left_type;
  _left_type left;

   typedef float _keep_type;
  _keep_type keep;

   typedef float _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> const> ConstPtr;

}; // struct action_expect_utility_

typedef ::beginner_tutorials::action_expect_utility_<std::allocator<void> > action_expect_utility;

typedef boost::shared_ptr< ::beginner_tutorials::action_expect_utility > action_expect_utilityPtr;
typedef boost::shared_ptr< ::beginner_tutorials::action_expect_utility const> action_expect_utilityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::action_expect_utility_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::action_expect_utility_<ContainerAllocator1> & lhs, const ::beginner_tutorials::action_expect_utility_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.keep == rhs.keep &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::action_expect_utility_<ContainerAllocator1> & lhs, const ::beginner_tutorials::action_expect_utility_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc73d065c693724e659082147922a7dc";
  }

  static const char* value(const ::beginner_tutorials::action_expect_utility_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc73d065c693724eULL;
  static const uint64_t static_value2 = 0x659082147922a7dcULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/action_expect_utility";
  }

  static const char* value(const ::beginner_tutorials::action_expect_utility_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left\n"
"float32 keep\n"
"float32 right\n"
;
  }

  static const char* value(const ::beginner_tutorials::action_expect_utility_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.keep);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct action_expect_utility_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::action_expect_utility_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::action_expect_utility_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "keep: ";
    Printer<float>::stream(s, indent + "  ", v.keep);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ACTION_EXPECT_UTILITY_H
